### ISSUE TITLE
По поводу работы

### ISSUE THREAD

**Issue by Dmitryi** [bigforcegun/workspace#1]
Здравствуйте, Марк.
Заранее извиняюсь, что пишу в github.
Я Дмитрий и 23 августа на вашу почту отправлял вакансии Ruby on Rails dev.
Хочу узнать вы готовы рассмотреть предложение о работе?

**Comment by bigforcegun** [comment]
:roll_eyes: 
Здравсвуйте. Сейчас перепроверю почту.
